### ISSUE TITLE
Do we need to add Renovate?

### ISSUE THREAD

**Issue by eugelogic** [eugelogic/matilda#28]
https://github.com/renovatebot/renovate

**Comment by crgeary** [comment]
Yeah we can do, can you set it up on this repo as I don't have access to do that.

I can create a configuration file for it though once it's set up.

I'll also use this opportunity to add prettier, to ensure it's formatted consistently.

**Comment by eugelogic** [comment]
I created a [pull request](https://github.com/eugelogic/matilda/pull/30) do you want to merge it yourself when you are ready?
