### ISSUE TITLE
header.html

### ISSUE THREAD

**Issue by eugelogic** [eugelogic/matilda#3]
the header.html file features the following. Do I need to remove it? (Prettier didn't allow me - lol)
```
    <main role="main"></main>
  </body>
</html>
```

**Comment by crgeary** [comment]
Oh. Prettier might not like it because the closing tags are all in another file.

I'll make it work in a different way for you.

**Comment by eugelogic** [comment]
oh actually I'm formatting the file with something else or not formatting at all I'm not sure.

Removing that code seems to work ok though

**Comment by crgeary** [comment]
I'll change it anyway.

It'll play nicer with editors if it's just the 1 file rather than 2 independent parts.
