### ISSUE TITLE
Nested folders

### ISSUE THREAD

**Issue by eugelogic** [eugelogic/matilda#7]
I don't seem to be able to create a folder inside `content`. Ideally I would gather together galleries inside a folder, categories inside another one, and leave at the top level pages like Home, About, Contact , etc

**Comment by crgeary** [comment]
That works, I tested out nested folders, but can you give me an example of what you are trying please.

**Comment by eugelogic** [comment]
You right, sorry.

I just tried again and it works like a charm 👍
